# Generated by Django 3.2.6 on 2021-08-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('product_Name', models.CharField(max_length=30)),
                ('product_price', models.FloatField(default=0)),
                ('product_desc', models.CharField(max_length=300)),
                ('product_pic', models.ImageField(default='', upload_to='Shop/Images')),
                ('product_Qty', models.IntegerField(default=1)),
                ('product_creation_time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
