# Generated by Django 3.2.6 on 2021-08-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_pic',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
