# Generated by Django 3.2.7 on 2021-09-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_alter_product_product_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_creation_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
