# Generated by Django 3.2.7 on 2021-09-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_remove_product_product_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SearchContent', models.CharField(max_length=100)),
                ('SearchTime', models.DateTimeField()),
                ('SearchHit', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_creation_time',
            field=models.DateField(),
        ),
    ]
