# Generated by Django 3.2.7 on 2021-09-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_rename_search_searchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_Name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='SearchTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
